### ISSUE TITLE
Issue bash on ubuntu on windows

### ISSUE THREAD

**Issue by therealprocyon** [ichinaski/pxl#10]
I got a problem with installing/setting it up on Bash on Ubuntu on Windows. It installs fine, but I get an error when running:

procyon@Raccoonbook:~$ pxl /mnt/c/Users/Procyon/Pictures/chattobuysupport.png
panic: invalid argument

goroutine 1 [running]:
panic(0x57f480, 0xc82000e4f0)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.main()
        /home/procyon/work/src/github.com/mattn/pxl/main.go:62 +0x2eb
procyon@Raccoonbook:~$

It won't run.

**Comment by ichinaski** [comment]
Hi, did you manage to solve the issue? I would suggest to use the latest version of Go and try again.

**Comment by therealprocyon** [comment]
Using the latest version of go:
```bash
panic: invalid argument

goroutine 1 [running]:
main.main()
        /home/procyon/go/src/github.com/ichinaski/pxl/main.go:79 +0x1fa```
